### ISSUE TITLE
program crash?

### ISSUE THREAD

**Issue by dangdkhanh** [neacsum/utf8#2]
Hi, I tried this code but the program crash:
string y="đặng dủy khánh siêu đại prố khủng khiếp";
const auto& result =  utf8::tolower(y.substr(1));
also i intend to add function utf8::tolower(char). 
can you suggest it directly?
I want to write a function similar to sentence case however the only thing that comes to mind is
utf8::tolower(string{char}) this is doing it indirectly and doesn't look very nice.

Thanks for your work.

**Comment by neacsum** [comment]
```C++
string y="đặng dủy khánh siêu đại prố khủng khiếp";
```
That should probably be:
```C++
string y=u8"đặng dủy khánh siêu đại prố khủng khiếp";`
```

Also for `y.substr(1)`: if you want to change to lower case all characters after the first one, you have to write something like:
```C++
  auto p = y.begin ();
  string s = utf8::narrow (utf8::rune (p));
  utf8::next (y, p);
  s += utf8::tolower (string (p, y.end ()));
```
Note that I've added a function `utf8::narrow(char32_t)`. Pull the latest version.

> also i intend to add function utf8::tolower(char).
Keep in mind that an UTF-8 character can be made of many (up to 4) characters. You could add a function `utf8::tolower (char32_t)` and that would be a nice addition.

**Comment by dangdkhanh** [comment]
Hi, Great!
your solution works as i expected.
