### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by HerrNamenlos123** [neacsum/utf8#3]
This seems to be a very neat library!
Have you considered adding CMake support?
Otherwise it would be quite cumbersome to ingegrate into existing projects

**Comment by neacsum** [comment]
This is a Windows specific project (the rest of the world has already moved to UTF-8) and in the Windows world there is only one significant toolchain. As such I don't see much benefit in adding CMake support. For integration with other packages I use my own package manager: https://github.com/neacsum/cpm

However if you want to add CMake support, please send a pull request. I will be happy to consider it.
